# training options
sampling_rate: 8000
frame_size: 200
frame_shift: 80
model_type: BLSTM
max_epochs: 10
gradclip: 5
batchsize: 10
hidden_size: 256
num_lstm_layers: 5
lr: 0.001
num_frames: 4000
num_speakers: 2
input_transform: logmel23_mn
optimizer: adam
context_size: 7
subsampling: 10
seed: 777
gpu: 0
